CREATE TABLE reservations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_id VARCHAR(50)                             NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    vehicle_id     BIGINT                                  NOT NULL,
    spot_id        VARCHAR(50)                             NOT NULL,
    start_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status         VARCHAR(20)                             NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    first_name VARCHAR(100)                            NOT NULL,
    last_name  VARCHAR(100)                            NOT NULL,
    phone      VARCHAR(20),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vehicules
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    license_plate VARCHAR(20)                             NOT NULL,
    make          VARCHAR(50),
    model         VARCHAR(50),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_vehicules PRIMARY KEY (id)
);

ALTER TABLE reservations
    ADD CONSTRAINT uc_reservations_reservationid UNIQUE (reservation_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE vehicules
    ADD CONSTRAINT uc_vehicules_licenseplate UNIQUE (license_plate);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicules (id);

ALTER TABLE vehicules
    ADD CONSTRAINT FK_VEHICULES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);