CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_id VARCHAR(50)                             NOT NULL,
    amount         DOUBLE PRECISION                        NOT NULL,
    method         VARCHAR(20)                             NOT NULL,
    status         VARCHAR(20)                             NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE rates
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zone_id     BIGINT                                  NOT NULL,
    hourly_rate DOUBLE PRECISION                        NOT NULL,
    currency    VARCHAR(10),
    CONSTRAINT pk_rates PRIMARY KEY (id)
);

CREATE TABLE receipts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id BIGINT                                  NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    content    TEXT,
    CONSTRAINT pk_receipts PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id  BIGINT                                  NOT NULL,
    gateway_ref VARCHAR(100),
    status      VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);